### ISSUE TITLE
Redirecting Issues in Showcase Site

### ISSUE THREAD

**Issue by aboarken** [joomla/showcase.joomla.org#12]
I do believe there is a redirecting issues in showcase directory admin site. Please check the attached picture.

![Showcase Login](https://user-images.githubusercontent.com/18500882/98358065-30dcd100-2037-11eb-91d8-0cf952f4cc8b.png)

**Comment by conconnl** [comment]
Not only admin.
I can login on the frontend, but if I logout it get into the same redirection loop.

After login on frontend I get redirected too:
https://showcase.joomla.org/8-users/23139-bes-octopoos.html

**Comment by sebastienlapoux** [comment]
Thanks! Looking on it.

**Comment by aboarken** [comment]
> Not only admin.
> I can login on the frontend, but if I logout it get into the same redirection loop.
> 
> After login on frontend I get redirected too:
> https://showcase.joomla.org/8-users/23139-bes-octopoos.html

Exactly, same here.

**Comment by sebastienlapoux** [comment]
The loop is due to the plugin "System - Force 2FA on Usergroup" when the user is part of a user group specified into this plugin and that the user has not enable 2FA.

So, this issue impacting only manager or admin. In my case, no issue because 2FA enable.

It was same issue for @sebastienheraud, no more issue after enable 2FA.

@ahmadm42 no more issue for you.

@conconnl can you please enable double authentification on your profil by editing it with the link on top right?

![image](https://user-images.githubusercontent.com/13470265/98372283-cb401300-203d-11eb-9166-4a903fbc9530.png)

@conconnl please alert me when it's done, to enable again the plugin.

To see how to fix the issue in long term purpose. We need to look 2FA on front-end too.

Thanks.

**Comment by conconnl** [comment]
I have 2FA enabled since it's possible.
In every Joomla website using all the core features it works perfectly.

**Comment by sebastienlapoux** [comment]
Thanks @conconnl . Plugin enable again. Please confirm that it works for you.

> In every Joomla website using all the core features it works perfectly.

On Showcase, the issue is on front-end, all ok for back-end. Because on front-end we're not managing users with Joomla, we have a ticket on this topic internally to allow SEBLOD to manage correctly 2FA in front-end. 
We will come back on this. In any case, would be nice to have an option to enable this plugin on back-end or front-end or both.

**Comment by conconnl** [comment]
@zero-24 maybe you can share your feedback on this as the developer.

**Comment by zero-24** [comment]
> We will come back on this. In any case, would be nice to have an option to enable this plugin on back-end or front-end or both.

There is no point in just enforcing it in the backend or just the frontend right? As an Super User can edit the Global config etc. from the frontend too right?

What I'm planing to fix is the backend redirecting from com_users to com_admin in the backend given that nowdays (after the inital release of my plugin) there is now support to configure 2fa in 3.9. too. So that should fix the admin redirect issue too right given that com_admin is aviable?

**Comment by zero-24** [comment]
The release has been made here: https://github.com/zero-24/plg_system_force2fausergroup/releases/tag/1.0.2

**Comment by sebastienlapoux** [comment]
Thanks a lot @zero-24 ! Agree with you.

Plugin updated on Showcase site.

@ahmadm42 I enable again some user groups into the plugin, can you please confirm that you have no more loop? Thanks in advance.

**Comment by aboarken** [comment]
@sebastienlapoux Hello, the issue came again. I am not able to login...same message appeared redirecting.

**Comment by sebastienlapoux** [comment]
Thanks @ahmadm42 . We return to the previous plugin configuration. Please try again.

**Comment by aboarken** [comment]
@sebastienlapoux ...Thank you. Be noted that some users are not loaded correctly as shown in the attached picture. This might be due to disabled users.
![Warning](https://user-images.githubusercontent.com/18500882/98593246-ea5fce80-22e3-11eb-8b0d-586bf8c924df.png)

**Comment by sebastienlapoux** [comment]
Thanks @ahmadm42 .

> Be noted that some users are not loaded correctly as shown in the attached picture. This might be due to disabled users.

Not the topic of this current issue. 
Not about disable users but about deleted users. In this case, please delete the site.

**Comment by aboarken** [comment]
Thanks you @sebastienlapoux
