### ISSUE TITLE
download and launch button are not aligned properly

### ISSUE THREAD

**Issue by vinayaks0031** [joomla/showcase.joomla.org#16]
in the phone, they are not aligned properly check this.
![case-study](https://user-images.githubusercontent.com/76878117/104011954-f3cac180-51d4-11eb-81c3-43d66e8075c6.jpg)

**Comment by sebastienlapoux** [comment]
Hi @vinayaks0031 ,

This issue is part of the common template used by joomla.org websites, same on https://community.joomla.org/

![Translations for Joomla!](https://user-images.githubusercontent.com/13470265/104941781-ce4b6e00-59b3-11eb-8432-a63623d2f11c.png)

@conconnl do you know please how to process in this case?

Thanks.

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by bisoladebiyi** [comment]
Hello, please can i work on this issue

**Comment by sebastienlapoux** [comment]
New version of the common template used by joomla.org websites is coming. Closing this issue.
